---
detectors:
  TooManyInstanceVariables:
    max_instance_variables: 6

directories:
  "app/application/services": # service scripts are funtional-oriented
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
